version: "3"
services:
  backend:
    build: ./
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      PORT: 8000
      MONGO_DB_URL: mongodb://mongo:27017/
    ports:
      - "8000:8000"
    command: yarn dev
    volumes:
      - ./:/app/
  mongo:
    image: mongo:4.2.9-bionic
    ports:
      - "27017:27017"
    volumes:
      - ./mongo:/data/db
